### ISSUE TITLE
Copying non ASCII symbols is not working.

### ISSUE THREAD

**Issue by Lourens-Rich** [pyrollo/display_modpack#13]
Minetest version: 0.4.17 (From backport-0.4 branch)
For example i want to copy text and paste them to another place.

![_2018-02-05_06-41-15](https://user-images.githubusercontent.com/22860367/35787486-93582354-0a3f-11e8-8f95-24e802a8616a.png)

![_2018-02-05_06-44-19](https://user-images.githubusercontent.com/22860367/35787519-ce8d4d64-0a3f-11e8-9601-683f5f5fa543.png)

**Comment by Lourens-Rich** [comment]
Hm... Sorry, it's problem for Minetest not for your mod. (Checked on default sign)

**Comment by pyrollo** [comment]
Yes unfortunatelly I experienced such problems with copy/paste. It seems, for now, the only way to paste your text is ... to type it :( 

As you say it's a game engine level problem.
