### ISSUE TITLE
Font with free license

### ISSUE THREAD

**Issue by Thomas--S** [pyrollo/display_modpack#17]
I suggest to switch to a font with free license, as our current default font seems to have a quite uncommon license which is not seen as Open Source / Free Software license.

Some possible alternatives could be:

- https://int10h.org/oldschool-pc-fonts/
- http://unifoundry.com/unifont.html
- https://fontstruct.com/fontstructions/show/723864/metro_sans

**Comment by pyrollo** [comment]
Thanks a lot for your suggestions! 
I'll change that soon as proposed fonts seems to fit to my requirements :
- Easily readable
- Pixel Font
- Variable width
- Accentuated letters, cyrillic, greek and other alphabets.

**Comment by pyrollo** [comment]
At last, a new font, under CC-BY-SA is used as default.

**Comment by Thomas--S** [comment]
Thanks for including this new font.

I found another font, which looks promising: https://fontstruct.com/fontstructions/show/145723/simple_rounded_pixel

I don't ask for this font to be included immediately, I only wanted to share the link with you.

**Comment by pyrollo** [comment]
Yes it looks very good but it has too few glyphs. Metro Sans font includes many accentuated letters, greek and cyrillic. A general purpose font should be able to display many languages (or your players may complain about it :) )
