### ISSUE TITLE
Suggestion: Wooden street sign?

### ISSUE THREAD

**Issue by sbrl** [pyrollo/display_modpack#18]
There are already green and yellow street signs, so what about a wooden one? It would go great to extend a directional sign like you can with the green one:

![image](https://user-images.githubusercontent.com/9929737/41653874-58ff5394-747f-11e8-9af0-b6f5363303c0.png)

**Comment by pyrollo** [comment]
At last there are new wooden sign and in particular one with the same shape as road signs (try long wooden sign).
