### ISSUE TITLE
Paramètre "height" non-reconnu

### ISSUE THREAD

**Issue by kilbith** [pyrollo/display_modpack#27]
Salut Pierre-Yves,

Je me suis aperçu que le paramètre `height` n'est pas reconnu dans l'API `display`, comme le mentionne la documentation : https://github.com/pyrollo/display_modpack/blob/master/display_api/API.md

J'ai trouvé la cause ici : https://github.com/pyrollo/display_modpack/blob/master/display_api/display.lua#L98

Il faut remplacer `top` par `height` du coup.

**Comment by pyrollo** [comment]
Hello JP,

Merci, je vais regarder ça !

Je suis en train de bosser sur le cahier des charges IGN.

Je vais surement avoir quelques questions à voir avec toi.

L'essentiel des questions viennent du besoin de faire quelque chose de 
réaliste, là ou Minetest ne l'est absolument pas.

Côté Kidscode, ils cherchent encore quelqu'un pour intervenir sur le 
moteur. Si tu as une idée a ce sujet, je suis preneur :)

P.Y


Le 2019-01-27 19:00, Jean-Patrick Guerrero a écrit :

**Comment by pyrollo** [comment]
Hello JP, 

Merci, je vais regarder ça !

**Comment by pyrollo** [comment]
Corrigé, le bon paramètre est "top", la documentation est mise à jour (commit 89fc7f863ddcf86eeeb129b65b0708f5bb6f4cb3 )
