### ISSUE TITLE
Duplication of mods

### ISSUE THREAD

**Issue by Thomas--S** [pyrollo/display_modpack#31]
Hello,

its seems like the most mods of this modpack exist twice now; there's one version in minetest-mods and the second one in this repository.

Which of those versions is considered the main version, i.e. where should pull requests and issues go to?

How are both versions supposed to stay in sync?

**Comment by pyrollo** [comment]
Hi

Now, you can propose pull requests on both minetest-mod mods and this modpack. I'll sync the changes anyway.

At the end, it will be better to send PR to minetest-mod as more people could be able to merge them.

**Comment by Thomas--S** [comment]
Thanks for your answer.

What do you think about referencing the minetest-mods versions of the mods in this modpack as git submodules, so that manual synchronisation isn't necessary anymore?

**Comment by pyrollo** [comment]
The big problem with submodules is that code is not included in downloadable tarball. That's a pity, and in my point of view, prevents their use. Instead I use subtree and just have to pull/push in order to sync.

As soon as Github make it possible to have submodules included in tar I'll use them !

**Comment by Thomas--S** [comment]
Ok. Thanks for the information! :+1:

**Comment by pyrollo** [comment]
You"re welcome !

Best thing that could happen to avoid such mess would be a nice and clever mod and dependencies management in minetest engine.
