### ISSUE TITLE
Strange text color/lighting behavior

### ISSUE THREAD

**Issue by tuedel** [pyrollo/display_modpack#35]
I've been experiencing a strange rendering bug since MT 5.0 where the actual text color of a display entity seems to be dependent on the environment light level at the time of its last update, and generally seems to change in weird/unexpected ways.

It seems to affect certain types of signs/displays more than others depending on their text color. I first noticed it with `signs_road:blue_street` and the scifi screens from https://github.com/pyrollo/digiterms, which also seem to exhibit a slightly different behavior regarding light level changes:

![display_lighting_bug](https://user-images.githubusercontent.com/1423212/64926275-00ffb800-d7fc-11e9-87e9-6e22eec5f291.gif)
(It's the same for artificial light, it was just easier to demonstrate using `/time`)

I'm not sure if this is a bug in the engine or in `display_api`. Any ideas? :)

**Comment by pyrollo** [comment]
Hi tuedel, 
That's interesing. When moving to MT5 I had the opposite bug : entity kept being lighten until hit.
I guess that has been fixed in MT5, inducing this behavior. Something must be missing in the entity spawn code.

**Comment by tuedel** [comment]
Salut @pyrollo! :)

The demonstration above was recorded using a fairly recent build of MT 5.1.0-dev (https://github.com/minetest/minetest/commit/1db3d252cff9e8d61fecf1052d7497813851da51)

**edit:** Oops, I misread your comment a bit.

**Comment by tuedel** [comment]
After some bisecting I found https://github.com/minetest/minetest/commit/787cd15c14b65f50b06c6b9ccecf28e937318430 (https://github.com/minetest/minetest/pull/6559) to be responsible for this. 

Before that commit everything looks fine to me, I was unable to reproduce the initial bug you describe.

**Comment by tuedel** [comment]
Issue: https://github.com/minetest/minetest/issues/9020
Fix: https://github.com/minetest/minetest/pull/9021

**Comment by pyrollo** [comment]
Thanks for that investigation !

Good to know this will be solved soon :)
