### ISSUE TITLE
High resolution textures

### ISSUE THREAD

**Issue by Golutazem** [pyrollo/display_modpack#4]
This is a feature request for high resolution textures or generated textures, suitable for use with HDX-512.

**Comment by pyrollo** [comment]
I guess it's about having 512x512 textures.

Can you give me a link to HDX-512 textures so I can get wood and metal textures from ?

Do you think font textures are already suitable ? (in the oposite case this is much extra work)

**Comment by pyrollo** [comment]
No answer for 6+ month. Closing the issue.
